export const SITES = [{
    id: 0,
    title: "Traveler's Keep",
    description: "Traveler's Keep is an app to help those with a wanderlust keep the memories of their adventures in organized. The user is presented with a map of places they've seen. When they click on the map they are navigated to a collection of photos and stories from that journey that they uploaded. Users have the option to add more photos and stories, and can create new vacations at any time. The site requires authentication(username/password). Users are only able to view their own photos after logging in. Feel free to create a test account and interact with the site!",
    involvement: 'Solo Concept Project: User interface, and API: designed and implemented by Diana.',
    siteURL: 'https://dianamcnulty.github.io/travelerskeep-client/',
    gitHubRepo: 'https://github.com/dianamcnulty/travelerskeep-client',
    screenShot: 'assets/images/ScreenShot-Map.png'},
  {id: 1,
    title: 'Jewelry Portfolio',
    description: "This clean and simple design is used to showcase the work of a jewelry designer who uses recycled materials to create works of art. Thumbnails on the right are clickable and bring up an image and description in the content section. (much like the page you're on right now). I also provided the photography.",
    involvement: 'Solo Concept Project- User interface designed and implemented by Diana',
    siteURL: 'https://dianamcnulty.github.io/Jewelry-Maker-s-Portfolio/',
    gitHubRepo: 'https://github.com/dianamcnulty/Jewelry-Maker-s-Portfolio',
    screenShot: 'assets/images/ScreenShot-jewelry.png'},
  {id: 2,
    title: 'Flight Log',
    description: "This single page app is for tracking paragliding/hang gliding flight data. Pilots can enter details about their flights, and retrieve a list of previous flights. They may also edit and delete previous flights. Certain stats are also displayed for the user, such as the number of flights they've had, total number of hours flown, what their longest or farthest flights were, etc. The app requires authentication. Users are only allowed to view their own flights. Feel free to create a test username/password at take it for a spin! Though this concept is intended for paragliding/hang gliding, it could easily be adapted for other activities; for example: a travel log, or run tracker.",
    involvement: 'Solo Concept Project- User interface, and API: designed and implemented by Diana',
    siteURL: 'https://dianamcnulty.github.io/flightlogclient/',
    gitHubRepo: 'https://github.com/dianamcnulty/flightlogclient',
    screenShot: 'assets/images/ScreenShot-flights.png'},
    {id: 3,
    title: "Photographer's Portfolio",
    description: "This site showcases the photography work of Ben Cloutier (my brother). It draws attention to the various categories of photography that he specializes in. His 'brand' has an edgy modern style. Keeping in mind the needs of this client, I chose neutral colors to compliment the photography rather than compete with it. Gold and Black provided the edgy contrast to reflect the photographers personality, but still worked well with his photos that had a more subdued hue. /n This site also features a 'site owner' dashboard so the photographer can easily edit the content of his site without needing any coding skills.",
    involvement: 'Solo Project: User interface, and API: designed and implemented by Diana',
    siteURL: 'https://dianamcnulty.github.io/bencloutierphotography/',
    gitHubRepo: 'https://github.com/dianamcnulty/bencloutierphotography',
    screenShot: 'assets/images/ScreenShot-ben.png'},
    {id: 4,
      title: "Musician's Website",
      description: "This is actually my own website for my musical endeavors. This project entailed designing and branding a site that was hosted on blogger.com. I added custom styling via css, and embedded third party widgets to enable users to purchase cd's and sheet music, or listen to music on the site. (For what it's worth, the photography, as well as cover art for sheetmusic and CD's on this site are also my designs.)",
      involvement: 'Imagery, and Branding and third party plug-ins(cd sales widget and shopping checkout are 3rd party plugins) were implemented by Diana. Site navigation and layout is inherited from the blogging platform.',
      siteURL: 'http://www.dianamcnulty.com',
      screenShot: 'assets/images/ScreenShot-flutist.png'},
    {id: 5,
      title: "Flute Quintet's Website",
      description: "Before I learned to code, I designed and branded this site using WIX, a platform for creating websites with a 'drag and drop' interface. The flute group wanted a site that was modern and 'sassy' and had all the features that musicians need, such as a 'news' page, sound clips, contact form etc.",
      involvement: 'Imagery, branding, layout, and content. No coding was necessary, this was strictly a design project',
      siteURL: 'http://www.pipinghotflutes.com',
      screenShot: 'assets/images/ScreenShot-piping.png'}
]
