export const SITES = [{
    id: 0,
    title: "Traveler's Keep",
    description: "Traveler's Keep is an app to help those with a wanderlust keep the memories of their adventures in organized. The user is presented with a map of places they've seen. When they click on the map they are navigated to a collection of photos and stories from that journey that they uploaded. Users have the option to add more photos and stories, and can create new vacations at any time.",
    involvement: 'Solo Project: User interface, and API: designed and implemented by Diana',
    siteURL: 'https://dianamcnulty.github.io/travelerskeep-client/',
    gitHubRepo: 'https://github.com/dianamcnulty/travelerskeep-client',
    screenShot: 'assets/images/ScreenShot-Map.png'},
  {id: 1,
    title: 'Flight Log',
    description: "This single page app is for tracking paragliding/hang gliding flight data. Pilots can enter details about their flights, and retrieve a list of previous flights. They may also edit and delete previous flights. Certain stats are also displayed for the user, such as the number of flights they've had, total number of hours flown, what their longest or farthest flights were, etc. The app requires authentication. Users are only allowed to view their own flights.",
    involvement: 'Solo Project: User interface, and API: designed and implemented by Diana',
    siteURL: 'https://dianamcnulty.github.io/flightlogclient/',
    gitHubRepo: 'https://github.com/dianamcnulty/flightlogclient',
    screenShot: 'assets/images/ScreenShot-flights.png'},
    {id: 2,
      title: 'Jewelry Portfolio',
      description: "This clean and simple design is used to showcase the work of a jewelry designer who uses recycled materials to create works of art. Thumbnails on the right are clickable and bring up an image and description in the content section. (much like the page you're on right now). I also provided the photography.",
      involvement: 'Solo Project: User interface designed and implemented by Diana',
      siteURL: 'https://dianamcnulty.github.io/Jewelry-Maker-s-Portfolio/',
      gitHubRepo: 'https://github.com/dianamcnulty/Jewelry-Maker-s-Portfolio',
      screenShot: 'assets/images/ScreenShot-jewelry.png'},
    {id: 3,
      title: "Musician's Website",
      description: "This is actually my website for my musical endeavors. This project entailed designing and branding a site that was hosted on blogger.com. I added custom styling via css, and embedded third party widgets to enable users to purchase cd's and sheet music, or listed to music on the site.",
      involvement: 'Imagery, and Branding and third party plug-ins implemented by Diana. Site navigation and layout is inherited from the blogging platform.',
      siteURL: 'http://www.dianamcnulty.com',
      screenShot: 'assets/images/ScreenShot-flutist.png'}
]
